dist:
  - trusty
sudo:
  - false
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - llvm-dev
      - libatomic-ops-dev
      - mono-xbuild
      - curl
      - make
      - tcc
      - libboost-dev
      - libqt4-dev
      - cmake
      - cmake-data
      - ninja-build
      - libboost-dev
      - libqt4-dev
      - exuberant-ctags
      - libelf-dev
      - libgmp-dev
      - zlib1g-dev
      - swig
env:
  - TESTS="r2pm -i armthumb"
  - TESTS="r2pm -i baleful"
  - TESTS="r2pm -i bcl"
  - TESTS="r2pm -i ba2"
  - TESTS="r2pm -i blackfin"
  - TESTS="r2pm -i blessr2"
#  - TESTS="r2pm -i bpf" [BR] https://travis-ci.org/radareorg/radare2-extras/builds/157522362
#  - TESTS="r2pm -i dlang" [BR] https://travis-ci.org/radareorg/radare2-extras/builds/157522362
# ONLY FOR LINUX  - TESTS="r2pm -i dirtycow"
  - TESTS="r2pm -i lang-duktape"
# - TESTS="git clone git://git.code.sf.net/p/libdwarf/code libdwarf-code && cd libdwarf-code && ./configure && make && cd .. && r2pm -i dwarf-parser && cd radare2-regressions && ./r2r dwarf && cd .. && r2pm -u libdwarf && rm -rf libdwarf-code" #need to remove libdwarf? or travis destroys the vm so no issue in that?
#  - TESTS="r2pm -i r2frida"
#  - TESTS="r2pm -i io-ewf" # https://github.com/travis-ci/apt-package-whitelist/issues/3205
#  - TESTS="r2pm -i keystone-lib && r2pm -i keystone && cd radare2-regressions && make keystone && cd .." [BR] https://travis-ci.org/radareorg/radare2-extras/builds/157522362
  - TESTS="r2pm -i mc6809"
  - TESTS="r2pm -i microblaze && cd radare2/test && make microblaze && cd ../.."
  - TESTS="r2pm -i msil"
  - TESTS="r2pm -i pcap"
  - TESTS="r2pm -i ppcdisasm"
  - TESTS="r2pm -i psosvm"
#  - TESTS="r2pm -i vala && r2pm -i valabind && r2pm -i r2api-python" [BR] https://travis-ci.org/radareorg/radare2-extras/builds/387043680
#  - TESTS="r2pm -i r2pipe-cs" [BR] https://travis-ci.org/radareorg/radare2-extras/builds/157522362
#  - TESTS="r2pm -i r2pipe-go" [BR] https://travis-ci.org/radareorg/radare2-extras/builds/387043680
  - TESTS="r2pm -i r2pipe-js"
  - TESTS="r2pm -i r2pipe-py"
  - TESTS="r2pm -i r2pipe-rb"
#  - TESTS="r2pm -i r2pipe-vala" https://travis-ci.org/radareorg/radare2-extras/builds/157522362
  - TESTS="r2pm -i radare2"
#  - TESTS="r2pm -i r2snow" https://travis-ci.org/radareorg/radare2-extras/jobs/199500082
#  - TESTS="r2pm -i radeco" [BR] https://travis-ci.org/radare/radare2-extras/builds/157522362
#  - TESTS="r2pm -i retdec"
  - TESTS="r2pm -i swf && make -C radare2/test swf"
#  - TESTS="r2pm -i m68k-net && cd radare2-regressions && make m68k-extras && cd .." [BR] https://travis-ci.org/radare/radare2-extras/builds/387043680
#  - TESTS="r2pm -i swig" Sorry. This package cannot be installed in your home.
  - TESTS="r2pm -i syms2elf"
#  - TESTS="r2pm -i tcc" [BR] https://travis-ci.org/radare/radare2-extras/builds/157522362
  - TESTS="r2pm -i unicorn-lib && r2pm -i unicorn" # need to do this properly
  - TESTS="r2pm -i vala"
#  - TESTS="r2pm -i valabind" [BR] https://travis-ci.org/radare/radare2-extras/builds/387043680
#  - TESTS="r2pm -i vapi" [BR] https://travis-ci.org/radare/radare2-extras/builds/387043680
  - TESTS="r2pm -i vc4"
  - TESTS="r2pm -i winapi"
  - TESTS="r2pm -i www-enyo"
#  - TESTS="r2pm -i www-m" [BR] https://travis-ci.org/radare/radare2-extras/builds/157522362
  - TESTS="r2pm -i www-p"
  - TESTS="r2pm -i www-t"
  - TESTS="r2pm -i x86udis"
  - TESTS="r2pm -i x86bea"
  - TESTS="r2pm -i x86tab"
  - TESTS="r2pm -i x86olly && cd radare2/test && make olly-extras && cd ../.."
  - TESTS="r2pm -i z80-nc"
  - TESTS="r2pm -i yara && r2pm -i yara-r2 && cd radare2/test && make yara && cd ../.."
  - TESTS="r2pm -i x86zyan"
language:
  - rust
rust:
  - stable
cache:
  - ccache
  - apt

before_script:
  - export WORKING_DIR=${TRAVIS_BUILD_DIR}/..
  - cd ${WORKING_DIR}
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 10
  - git clone https://github.com/radareorg/radare2 && cd radare2
  - export CC=gcc-7
  - ./configure --prefix=${WORKING_DIR}/install > /dev/null
  - make -s -j2 > /dev/null
  - make install > /dev/null
  - cd ..
  - export PATH=${WORKING_DIR}/install/bin:${PATH}
  - export LD_LIBRARY_PATH=${WORKING_DIR}/install/lib:${LD_LIBRARY_PATH}
  - export LIBR_INCLUDE=${WORKING_DIR}/radare2/libr/include
  - export LIBR_UTIL=${WORKING_DIR}/radare2/libr/util
  - export PKG_CONFIG_PATH=${WORKING_DIR}/radare2/pkgcfg
  - export GOPATH=${WORKING_DIR}/
  - r2pm init
  - export R2PM_GITDIR=${WORKING_DIR}
  - cd radare2-extras
  - ./configure --prefix=${WORKING_DIR}/install
  - cd ..

script:
  - eval $TESTS
